hub:
  config:
    Authenticator:
      allowed_users:
        - daniel
        - aly
        - johannes
        - james
        - michael
        - nick
        - arkadeep
      admin_users:
        - daniel
        - aly
        - johannes
        - james
        - michael
        - nick
        - arkadeep
    DummyAuthenticator:
      password: liegroup 
    JupyterHub:
      authenticator_class: dummy
      admin_access: true
      allow_named_servers: true
      named_server_limit_per_user: 5

proxy:
  https:
    enabled: true
    hosts:
      - lie.adelodun.uk
    letsencrypt:
      contactEmail: daniel@stemstudios.tv

cull:
  enabled: false

singleuser:
  defaultUrl: "/lab"
  image:
    name: danielade/liegroup
    tag: v0.1.0
  lifecycleHooks:
    postStart:
      exec:
        command:
          [
            "gitpuller",
            "https://github.com/DanielAdelodun/Lie-Groups-to-Particle-Physics",
            "main",
            "Lie-Groups-to-Particle-Physics",
          ] 
  profileList:
    - display_name: "Animation Tools"
      description: "A jupyterlab environment containing tools for mathematical animation."
      default: true
    - display_name: "Animation Tools + Sagemath"
      description: "(Broken) Sagemath has some pretty cool functionality. This enviornment contains all the animation tools, plus sage."
      kubespawner_override:
        image: danielade/liegroup-sagemath:v0.1.0
        lifecycle_hooks:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  gitpuller https://github.com/DanielAdelodun/Lie-Groups-to-Particle-Physics main Lie-Groups-to-Particle-Physics;
    - display_name: "Animation + Datascience Tools"
      description: "Animation environment with lots of useful tools - courtesy of Scipy, Julia and R."
      kubespawner_override:
        image: danielade/liegroup-datascience:v0.1.0
        lifecycle_hooks:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  gitpuller https://github.com/DanielAdelodun/Lie-Groups-to-Particle-Physics main Lie-Groups-to-Particle-Physics;
    - display_name: "Animation + Datascience + Sagemath"
      description: "(Broken) Probably a bit much..."
      kubespawner_override:
        image: danielade/liegroup-extra:v0.1.0
        lifecycle_hooks:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  gitpuller https://github.com/DanielAdelodun/Lie-Groups-to-Particle-Physics main Lie-Groups-to-Particle-Physics;
    - display_name: "Datascience environment"
      description: "If you want some additional tools. Comes with Scipy, R, and Julia. Does not include animation tools."
      kubespawner_override:
        image: jupyter/datascience-notebook:hub-1.4.1
        lifecycle_hooks:
          postStart:
            exec:
              command:
                - "echo"
                - "Ready to Rock"
    - display_name: "Minimal Python"
      description: "Just Python"
      kubespawner_override:
        image: jupyter/minimal-notebook:hub-1.4.1
        lifecycle_hooks:
          postStart:
            exec:
              command:
                - "echo"
                - "Ready to Roll"
